import os
import logging
from typing import List

from fastmcp import FastMCP
from dotenv import load_dotenv

from src.rag.config import settings
from src.rag.factory import ModelFactory
from src.rag.engine import RAGQueryEngine
from src.rag.ingest import DocumentIngestor
from src.rag.vectorstore import VectorStoreManager

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

# Load environment variables if not handled entirely by pydantic
load_dotenv()

# Instantiate FastMCP server
mcp = FastMCP("RAG-Server")

logger.info(f"Initializing RAG Server models in '{settings.execution_mode}' mode.")

# 1. Instantiate Models (Lazy-loaded locally but shared entirely by server state)
try:
    embeddings_model = ModelFactory.get_embeddings()
    llm = ModelFactory.get_llm()
    vs_manager = VectorStoreManager(embeddings=embeddings_model)
    retriever = vs_manager.get_retriever(k=3)
    engine = RAGQueryEngine(llm=llm, retriever=retriever)
except Exception as e:
    logger.error(f"Failed to initialize RAG components: {e}")
    # Fail gracefully on startup. MCP Server will still start but tools will fail contextually.
    embeddings_model, llm, vs_manager, retriever, engine = None, None, None, None, None


@mcp.tool()
def ingest_directory(directory_path: str) -> str:
    """
    Scans the provided directory path for supported documents (.txt, .md, .pdf), chunks them, 
    and ingests them into the persistent Chroma DB vector store for future context retrieval.
    This safely prevents duplicates based on document source and string content.
    
    Args:
        directory_path: The absolute or relative local directory to parse (e.g. "./docs").
    
    Returns:
        A success string indicating the number of chunks successfully ingested.
    """
    if not vs_manager:
        return "Error: RAG components failed to initialize. Check server logs."

    logger.info(f"Ingesting directory: {directory_path}")
    if not os.path.exists(directory_path):
        return f"Error: Directory '{directory_path}' does not exist on the host filesystem."
    
    ingestor = DocumentIngestor(
        directory_path=directory_path,
        chunk_size=1000,
        chunk_overlap=200
    )
    chunks = ingestor.process_directory()
    
    if not chunks:
        return f"No valid documents found or processed in '{directory_path}'."
        
    vs_manager.add_documents(chunks)
    return f"Success! Ingested and stored {len(chunks)} document chunk(s) from '{directory_path}'."


@mcp.tool()
def search_memory(query: str, k: int = 3) -> List[str]:
    """
    Directly queries the vector database using semantic similarity to find the most relevant chunks 
    associated with the provided query. This does NOT trigger the LLM for synthesis, it safely 
    returns raw structural strings.
    
    Args:
        query: The semantic search string to query against the vector store.
        k: The number of maximum relevant chunks to return (default: 3).
        
    Returns:
        A list of string literals containing the raw text from the top ranked documents.
    """
    if not vs_manager:
        return ["Error: RAG components failed to initialize. Check server logs."]

    logger.info(f"Searching memory for: {query}")
    tmp_retriever = vs_manager.get_retriever(k=k)
    docs = tmp_retriever.invoke(query)
    
    if not docs:
        return ["No relevant context found in the memory database."]
    
    # Return string representations of the page content
    return [d.page_content for d in docs]


@mcp.tool()
def ask_assistant(query: str) -> str:
    """
    Performs full Retrieval-Augmented Generation (RAG). Extracts relevant context from memory and passes
    it along with the query to the active LLM (Ollama offline or Gemini online) to generate a synthesized answer.
    
    Args:
        query: The user's question or prompt meant for the LLM.
        
    Returns:
        The text response generated by the LLM based strictly on the retrieved context.
    """
    if not engine:
        return "Error: RAG query engine failed to initialize. Check server logs."

    logger.info(f"Asking RAG Assistant: {query}")
    try:
        result = engine.query(query)
        answer = result.get('answer', "No answer could be generated.")
        return answer
    except Exception as e:
        logger.error(f"Error executing ask_assistant via LLM: {e}")
        return f"Error generating answer: {str(e)}"


if __name__ == "__main__":
    logger.info("Starting RAG MCP Server...")
    mcp.run()

